In [1]:
import xarray as xr
import fsspec

# CM4
fs_osn = fsspec.filesystem(
    "s3",
    profile="ocean_emulator",  ## This is the profile name you configured above.
)

In [2]:
mapper = fs_osn.get_mapper("emulators/ai2_colab/2024-11-01-CM4-pre-industrial-control-simulation/ocean_5daily.zarr")
data = xr.open_zarr(mapper, consolidated=True)
data

<xarray.Dataset>
Dimensions:     (time: 14600, yh: 1080, xh: 1440, nv: 2, z_l: 19, xq: 1440,
                 yq: 1080, z_i: 20)
Coordinates:
  * nv          (nv) float64 1.0 2.0
  * time        (time) object 0151-01-06 00:00:00 ... 0351-01-01 00:00:00
  * xh          (xh) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * xq          (xq) float64 -299.6 -299.3 -299.1 -298.9 ... 59.66 59.91 60.16
  * yh          (yh) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * yq          (yq) float64 -80.35 -80.27 -80.19 -80.11 ... 89.78 89.89 90.0
  * z_i         (z_i) float64 0.0 5.0 15.0 30.0 ... 4.5e+03 5.5e+03 6.5e+03
  * z_l         (z_l) float64 2.5 10.0 22.5 40.0 ... 3.1e+03 4e+03 5e+03 6e+03
Data variables: (12/23)
    average_DT  (time) timedelta64[ns] dask.array<chunksize=(14600,), meta=np.ndarray>
    evs         (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfds        (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hflso       (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfsifrazil  (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfsso       (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    ...          ...
    tos         (time, yh, xh) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    uo          (time, z_l, yh, xq) float64 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>
    ustar       (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    vo          (time, z_l, yq, xh) float64 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>
    wfo         (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    zos         (time, yh, xh) float64 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
Attributes:
    associated_files:  areacello: 01510101.ocean_static.nc
    grid_tile:         N/A
    grid_type:         regular
    title:             CM4_piControl_C_noBLING_H

In [3]:
file = fs_osn.open("emulators/ai2_colab/2024-08-01-sample-raw-CM4-data/gaussian_grid_180_by_360.nc", "rb")
gaussian_grid = xr.open_dataset(file, engine="h5netcdf")
gaussian_grid

<xarray.Dataset>
Dimensions:    (grid_y: 181, grid_x: 361, grid_yt: 180, grid_xt: 360)
Dimensions without coordinates: grid_y, grid_x, grid_yt, grid_xt
Data variables:
    grid_lat   (grid_y, grid_x) float64 ...
    grid_latt  (grid_yt, grid_xt) float64 ...
    grid_lon   (grid_y, grid_x) float64 ...
    grid_lont  (grid_yt, grid_xt) float64 ...
Attributes:
    long_name:  Latitude cell edge
    units:      degrees
    history:    180 by 360 Gaussian grid in format needed for GFDL fregrid to...

In [4]:
file = fs_osn.open("emulators/ai2_colab/2024-11-11-static-data/ocean_hgrid.nc", "rb")
hgrid = xr.open_dataset(file, engine="scipy")
hgrid

<xarray.Dataset>
Dimensions:   (nyp: 2161, nxp: 2881, ny: 2160, nx: 2880)
Dimensions without coordinates: nyp, nxp, ny, nx
Data variables:
    angle_dx  (nyp, nxp) float64 ...
    area      (ny, nx) float64 ...
    dx        (nyp, nx) float64 ...
    dy        (ny, nxp) float64 ...
    tile      |S255 ...
    x         (nyp, nxp) float64 ...
    y         (nyp, nxp) float64 ...

In [5]:
file = fs_osn.open("emulators/ai2_colab/2024-11-11-static-data/ocean_static_no_mask_table.nc", "rb")
static_table = xr.open_dataset(file, engine="scipy")
static_table

<xarray.Dataset>
Dimensions:       (xh: 1440, yh: 1080, time: 1, xq: 1440, yq: 1080)
Coordinates:
  * xh            (xh) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * yh            (yh) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * time          (time) object 1900-01-01 00:00:00
  * xq            (xq) float64 -299.6 -299.3 -299.1 -298.9 ... 59.66 59.91 60.16
  * yq            (yq) float64 -80.35 -80.27 -80.19 -80.11 ... 89.78 89.89 90.0
Data variables: (12/27)
    areacello     (yh, xh) float32 ...
    deptho        (yh, xh) float32 ...
    hfgeou        (yh, xh) float32 ...
    sftof         (yh, xh) float32 ...
    Coriolis      (yq, xq) float32 ...
    geolon        (yh, xh) float32 ...
    ...            ...
    dxCv          (yq, xh) float32 ...
    dyCv          (yq, xh) float32 ...
    areacello_cu  (yh, xq) float32 ...
    areacello_cv  (yq, xh) float32 ...
    areacello_bu  (yq, xq) float32 ...
    basin         (yh, xh) int32 ...
Attributes:
    filename:   19000101.ocean_static.nc
    title:      OM4_SIS2_cgrid_025
    grid_type:  regular
    grid_tile:  N/A

### Tests

In [6]:
assert hgrid.nyp.size == (2 * data.yh.size + 1)
assert hgrid.nxp.size == (2 * data.xh.size + 1)

In [7]:
import numpy as np
print(np.unique(static_table.wet.values))

mapper = fs_osn.get_mapper("emulators/ai2_colab/2024-11-01-CM4-pre-industrial-control-simulation/ocean_static.zarr")
static_ = xr.open_zarr(mapper, consolidated=True)
print(np.unique(static_.wet.values))
static_


[0. 1.]
[0. 1.]


<xarray.Dataset>
Dimensions:       (yq: 1080, xq: 1440, yh: 1080, xh: 1440, time: 1)
Coordinates:
  * time          (time) object 0001-01-01 00:00:00
  * xh            (xh) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * xq            (xq) float64 -299.6 -299.3 -299.1 -298.9 ... 59.66 59.91 60.16
  * yh            (yh) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * yq            (yq) float64 -80.35 -80.27 -80.19 -80.11 ... 89.78 89.89 90.0
Data variables: (12/26)
    Coriolis      (yq, xq) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    areacello     (yh, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    areacello_bu  (yq, xq) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    areacello_cu  (yh, xq) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    areacello_cv  (yq, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    deptho        (yh, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    ...            ...
    hfgeou        (yh, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    sftof         (yh, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    wet           (yh, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    wet_c         (yq, xq) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    wet_u         (yh, xq) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
    wet_v         (yq, xh) float32 dask.array<chunksize=(1080, 1440), meta=np.ndarray>
Attributes:
    NCO:                        netCDF Operators version 5.0.1 (Homepage = ht...
    grid_tile:                  N/A
    grid_type:                  regular
    history:                    Wed Oct  2 18:53:02 2024: ncks -A -m -v areac...
    history_of_appended_files:  Wed Oct  2 18:53:02 2024: Appended file 01510...
    title:                      CM4_piControl_C_noBLING_H

### Processing starts here

In [8]:
import fsspec
import numpy as np
import xarray as xr
from xarray_schema import SchemaError
from xgcm import Grid


In [9]:
ds = data
ds_grid = static_table
ds_super_grid = hgrid

### Depth handling

In [10]:
if "z_i" in ds.coords:
    ds = ds.rename({"z_i": "ilev", "z_l": "lev"})
    dz = xr.DataArray(
        ds.ilev.diff("ilev").values,
        dims=["lev"],
    ).astype("int64")
    ilev = ds["ilev"]
else:
    # add vertical info
    dz = xr.DataArray(
        [
            5,
            10,
            15,
            20,
            30,
            50,
            70,
            100,
            150,
            200,
            250,
            300,
            400,
            500,
            600,
            800,
            1000,
            1000,
            1000,
        ],
        dims=["lev"],
    )
    ilev = xr.DataArray(
        [
            0,
            5,
            15,
            30,
            50,
            80,
            130,
            200,
            300,
            450,
            650,
            900,
            1200,
            1600,
            2100,
            2700,
            3500,
            4500,
            5500,
            6500,
        ],
        dims=["ilev"],
    )

ds = ds.assign_coords(dz=dz)

### Interpolation

In [11]:

def interpolate_to_cell_centers(
    ds: xr.Dataset,
    like: xr.DataArray,
    grid: Grid,
):
    """Interplate variables defined on cell boundaries to cell centers.

    Args:
        ds: Input dataset.
        like: The data array to use as a template for the interpolation.
        grid: The grid object which will perform the interplation.

    """
    xh, yh = grid.axes["X"].coords["center"], grid.axes["Y"].coords["center"]
    xq, yq = grid.axes["X"].coords["right"], grid.axes["Y"].coords["right"]
    ds_interpolated = xr.Dataset()
    for var in ds.data_vars:
        da = ds[var]
        if set([xh, yh]).issubset(da.dims):
            ds_interpolated[var] = da
        elif xq in da.dims or yq in da.dims:
            # fill the velocities with 0 before interpolation to avoid mismatches in nans
            ds_interpolated[var] = grid.interp_like(da.fillna(0), like)
        if var in ds_interpolated:
            ds_interpolated[var].attrs = da.attrs

    return ds_interpolated


# trim excess padding
if ds["xq"].size == ds["xh"].size + 1:
    ds = ds.isel(xq=slice(1, None))
if ds["yq"].size == ds["yh"].size + 1:
    ds = ds.isel(yq=slice(1, None))

grid = Grid(
    ds,
    coords={
        "X": {"center": "xh", "right": "xq"},
        "Y": {"center": "yh", "right": "yq"},
    },
    boundary="extend",
    periodic=["xh", "xq"],
)
ds_interpolated = interpolate_to_cell_centers(ds, ds.thetao, grid)

### Masking

In [12]:

def _pick_first_element_of_missing_dims(mask: xr.DataArray, data: xr.DataArray):
    missing_dims = [di for di in mask.dims if di not in data.dims]
    if len(missing_dims) == 0:
        return mask
    else:
        print(f"Missing dimensions: {missing_dims}")
        return mask.isel({di: 0 for di in missing_dims})


def apply_mask(ds: xr.Dataset, mask: xr.DataArray):
    """applies mask to same and lower dimensional data"""
    ds_out = xr.Dataset(attrs=ds.attrs)
    for var in ds.data_vars:
        data = ds[var]
        mask_pruned = _pick_first_element_of_missing_dims(mask, data)
        ds_out[var] = data.where(mask_pruned)
    return ds_out

# remove the same areas as for the tracers again
tracer_wetmask = ~np.isnan(ds_interpolated.thetao.isel(time=0)).drop_vars("time")
ds = apply_mask(ds_interpolated, tracer_wetmask)
ds = ds.assign_coords(ilev=ilev, wetmask=tracer_wetmask)

ds_grid = ds_grid.drop_vars("time")
ds_grid = ds_grid.set_coords([v for v in ds_grid.data_vars])
# ds_grid
# ds = xr.merge([ds, ds_grid])
ds = ds.assign_coords(
    lon=ds_grid.geolon, lat=ds_grid.geolat, areacello=ds_grid.areacello
)

Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']
Missing dimensions: ['lev']


In [13]:
# drop (for now) all the coords on non-tracer position
required_coords = [
    "lon",
    "time",
    "xh",
    "lat",
    "ilev",
    "lev",
    "yh",
    "areacello",
    "wetmask",
    "dz",
]
drop_coords = [co for co in ds.coords.keys() if co not in required_coords]
ds = ds.drop(drop_coords)

### Super grid conversion

In [14]:

def convert_super_grid(ds_super_grid: xr.Dataset):
    h_rename = {"nyp": "yh", "nxp": "xh"}
    b_rename = {"nyp": "yh_b", "nxp": "xh_b"}

    h_indicies = dict(nyp=slice(1, None, 2), nxp=slice(1, None, 2))
    b_indicies = dict(
        nyp=slice(0, None, 2), nxp=slice(0, None, 2)
    )  # locations of 'bound variables required by xesmf

    angle_h = ds_super_grid.angle_dx.isel(**h_indicies).rename(h_rename)
    lon_h = ds_super_grid.x.isel(**h_indicies).rename(h_rename)
    lat_h = ds_super_grid.y.isel(**h_indicies).rename(h_rename)

    lon_b = ds_super_grid.x.isel(**b_indicies).rename(b_rename)
    lat_b = ds_super_grid.y.isel(**b_indicies).rename(b_rename)
    return angle_h, lon_h, lat_h, lon_b, lat_b


a, lon, lat, lon_b, lat_b = convert_super_grid(ds_super_grid)
lon_expected = ds_grid.load().geolon.reset_coords(drop=True).drop(["xh", "yh"])
lat_expected = ds_grid.load().geolat.reset_coords(drop=True).drop(["xh", "yh"])

# asser that the grid positions extracted are correct (this should maybe live in a test for an upstream function?)
xr.testing.assert_allclose(lon, lon_expected)
xr.testing.assert_allclose(lat, lat_expected)

ds = ds.assign_coords(lon_b=lon_b, lat_b=lat_b, angle=a, lon=lon, lat=lat)
ds = ds.rename({"xh": "x", "yh": "y", "xh_b": "x_b", "yh_b": "y_b"})
if "time_bnds" in ds.data_vars:
    ds = ds.drop_vars(["time_bnds"])
ds = ds.astype(np.float32)
# higher precision for the area
ds = ds.assign_coords(areacello=ds.areacello.astype("float64"))

### Validation

In [15]:

from xarray_schema import CoordsSchema, DataArraySchema, DatasetSchema

### Preprocessing Stage
vars_3d = ["so", "thetao", "uo", "vo"]
vars_2d = ["hfds", "tauuo", "tauvo", "zos"]
ds_processed_coords_schema = CoordsSchema(
    {
        "wetmask": DataArraySchema(dtype=bool, dims=["lev", "y", "x"]),
        "lon_b": DataArraySchema(
            dtype="float64", shape=(1081, 1441), dims=["y_b", "x_b"]
        ),
        "lat_b": DataArraySchema(
            dtype="float64", shape=(1081, 1441), dims=["y_b", "x_b"]
        ),
        "lon": DataArraySchema(dtype="float64", shape=(1080, 1440), dims=["y", "x"]),
        "lat": DataArraySchema(dtype="float64", shape=(1080, 1440), dims=["y", "x"]),
        "angle": DataArraySchema(dtype="float64", shape=(1080, 1440), dims=["y", "x"]),
        "areacello": DataArraySchema(
            dtype="float64", shape=(1080, 1440), dims=["y", "x"]
        ),
        "dz": DataArraySchema(dtype="int64", shape=(19,), dims=["lev"]),
        "lev": DataArraySchema(dtype="float64", shape=(19,), dims=["lev"]),
        "ilev": DataArraySchema(dtype="float64", shape=(20,), dims=["ilev"]),
        "x": DataArraySchema(dtype="float64", shape=(1440,), dims=["x"]),
        "y": DataArraySchema(dtype="float64", shape=(1080,), dims=["y"]),
        "time": DataArraySchema(
            dims=["time"]
        ),  # can I check that this is actually cftime?
    }
)
ds_processed_schema = DatasetSchema(
    {
        k: DataArraySchema(dtype="float32", dims=["time", "y", "x"], name=k)
        for k in vars_2d
    }
    | {
        k: DataArraySchema(dtype="float32", dims=["time", "lev", "y", "x"], name=k)
        for k in vars_3d
    }
)

### Input Stage - These are ignored for now
# vars_3d = ["so", "thetao", "uo", "vo"]
# vars_2d = ["hfds", "tauuo", "tauvo", "zos"]
# TODO: add flux components + ice variables         "sithick","siconc",
# ds_input_coords_schema = CoordsSchema(
#     {
#         "wetmask": DataArraySchema(dtype=bool, dims=["lev", "y", "x"]),
#         "ocean_fraction": DataArraySchema(dtype="float64", dims=["lev", "y", "x"]),
#         "lon_b": DataArraySchema(
#             dtype="float64", shape=(181, 361), dims=["y_b", "x_b"]
#         ),
#         "lat_b": DataArraySchema(
#             dtype="float64", shape=(181, 361), dims=["y_b", "x_b"]
#         ),
#         "lon": DataArraySchema(dtype="float64", shape=(180, 360), dims=["y", "x"]),
#         "lat": DataArraySchema(dtype="float64", shape=(180, 360), dims=["y", "x"]),
#         "areacello": DataArraySchema(
#             dtype="float64", shape=(180, 360), dims=["y", "x"]
#         ),
#         "dz": DataArraySchema(dtype="int64", shape=(19,), dims=["lev"]),
#         "lev": DataArraySchema(dtype="float64", shape=(19,), dims=["lev"]),
#         "x": DataArraySchema(dtype="float64", shape=(360,), dims=["x"]),
#         "y": DataArraySchema(dtype="float64", shape=(180,), dims=["y"]),
#         "time": DataArraySchema(
#             dims=["time"]
#         ),  # can I check that this is actually cftime?
#     }
# )

# ds_input_attrs_schema = AttrsSchema({"m2lines/ocean-emulators_git_hash":'dummy'})

# ds_input_schema = DatasetSchema(
#     {
#         k: DataArraySchema(dtype="float32", dims=["time", "y", "x"], name=k)
#         for k in vars_2d
#     }
#     | {
#         k: DataArraySchema(dtype="float32", dims=["time", "lev", "y", "x"], name=k)
#         for k in vars_3d
#     },
# )

### Prediction
ds_prediction_schema = DatasetSchema()
ds_prediction_coords_schema = CoordsSchema({"time": DataArraySchema(dims=["time"])})


In [16]:
try:
    ds_processed_schema.validate(ds)
    ds_processed_coords_schema.validate(
        ds.coords
    )  # this should be part of the dataset validation (maybe raise an issue/pr?)
    
except SchemaError as err:
    print(f"Failed validation with error: {str(err)}")

#### Nan check

In [17]:

def split_2d_3d(ds: xr.Dataset):
    ds_2d = xr.Dataset({v: ds[v] for v in ds.data_vars if "lev" not in ds[v].dims})
    ds_3d = xr.Dataset({v: ds[v] for v in ds.data_vars if "lev" in ds[v].dims})
    return ds_2d, ds_3d

ds_nan_test_2d, ds_nan_test_3d = split_2d_3d(ds)

In [18]:
from tqdm.auto import tqdm  # Add this import at the top

def _find_index_for_true(da_bool: xr.DataArray, check_dims):
    """Find slices along all dimensions within a boolean array that have any True value"""
    all_dims = [di for di in check_dims if di in da_bool.dims]

    true_found_index = {}
    for dim in tqdm(all_dims, desc=f"Checking dimensions - {all_dims}"):
        other_dims = [di for di in da_bool.dims if di != dim]
        test = da_bool.any(other_dims).load()
        index = da_bool[dim].isel({dim: test})
        true_found_index[dim] = index.data
    return true_found_index


def ensure_nan_consistency(ds: xr.Dataset, name="None"):
    """Test the consistency of nan values in the dataset across variables and time
    (compared to a reference at time=0)."""
    print(f"Converting dataset to array...")
    ds = ds.to_array()
    ref = ds.isel(time=0)
    
    print(f"Checking variable consistency...")
    first_var = np.isnan(ref.isel(variable=0))
    all_var = np.isnan(ref).all(["variable"])
    a = first_var != all_var

    print(f"Checking index consistency...")
    index = _find_index_for_true(a, check_dims=list(a.dims))
    print(index)
    if not all(len(v) == 0 for v in index.values()):
        raise ValueError(
            "Found non-matching nan values between variables on the first time step."
        )

    print(f"Checking temporal consistency...")
    b = np.isnan(ref) != np.isnan(ds)
    
    print(f"Checking index consistency...")
    index = _find_index_for_true(b, check_dims=["variable", "time"])

    if not all(len(v) == 0 for v in index.values()):
        raise ValueError(
            f"{name}:Found nonmatching nans compared to first time step in the following indexes {index}"
        )

In [19]:
print("2D consistency check")
# ensure_nan_consistency(ds_nan_test_2d, "2D nan consistency check")


2D consistency check


In [20]:
print("3D consistency check")
# ensure_nan_consistency(ds_nan_test_3d, "3D nan consistency check")

3D consistency check


##### Nan check tester

In [21]:
import xarray as xr
import numpy as np

da_bool = xr.DataArray(
    [[True, False, True], [False, True, False]],
    dims=["x", "y"],
    coords={"x": [10, 20], "y": [1, 2, 3]},
)

other_dims = ["y"]  # Reduce along "y"

test = da_bool.any(other_dims)
print(test)

<xarray.DataArray (x: 2)>
array([ True,  True])
Coordinates:
  * x        (x) int64 10 20


In [22]:
dim = "x"
index = da_bool[dim].isel({dim: test})
print(index)

<xarray.DataArray 'x' (x: 2)>
array([10, 20])
Coordinates:
  * x        (x) int64 10 20


### Continue 

In [21]:
idepth_data = {}

for i, depth in enumerate(ds['ilev'].values):
    idepth_data[f"idepth_{i}"] = xr.DataArray(depth)
    idepth_data[f"idepth_{i}"].attrs["units"] = "meters"
    idepth_data[f"idepth_{i}"].attrs["long_name"] = f"Depth at interface level-{i}"

idepth_ds = xr.Dataset(idepth_data)
idepth_ds


<xarray.Dataset>
Dimensions:    ()
Data variables: (12/20)
    idepth_0   float64 0.0
    idepth_1   float64 5.0
    idepth_2   float64 15.0
    idepth_3   float64 30.0
    idepth_4   float64 50.0
    idepth_5   float64 80.0
    ...         ...
    idepth_14  float64 2.1e+03
    idepth_15  float64 2.7e+03
    idepth_16  float64 3.5e+03
    idepth_17  float64 4.5e+03
    idepth_18  float64 5.5e+03
    idepth_19  float64 6.5e+03

In [22]:
print(f"Preprocessed size: {ds.nbytes / 1e9:.1f} GB")

Preprocessed size: 8537.5 GB


In [23]:
attrs = {}
for var in ds.data_vars:
    attrs[var] = ds[var].attrs
attrs


{'evs': {'cell_measures': 'area: areacello',
  'cell_methods': 'area:mean yh:mean xh:mean time: mean',
  'long_name': 'Water Evaporation Flux Where Ice Free Ocean over Sea',
  'standard_name': 'water_evaporation_flux',
  'time_avg_info': 'average_T1,average_T2,average_DT',
  'units': 'kg m-2 s-1'},
 'hfds': {'cell_measures': 'area: areacello',
  'cell_methods': 'area:mean yh:mean xh:mean time: mean',
  'long_name': 'Surface ocean heat flux from SW+LW+latent+sensible+masstransfer+frazil+seaice_melt_heat',
  'standard_name': 'surface_downward_heat_flux_in_sea_water',
  'time_avg_info': 'average_T1,average_T2,average_DT',
  'units': 'W m-2'},
 'hflso': {'cell_measures': 'area: areacello',
  'cell_methods': 'area:mean yh:mean xh:mean time: mean',
  'long_name': 'Surface Downward Latent Heat Flux due to Evap + Melt Snow/Ice',
  'standard_name': 'surface_downward_latent_heat_flux',
  'time_avg_info': 'average_T1,average_T2,average_DT',
  'units': 'W m-2'},
 'hfsifrazil': {'cell_measures': 'a

### Rotate vectors

In [24]:

def rotate_vectors(u, v, angle):
    """rotates vector components u and v using `angle`
    (assumed to be defined in deg, and in the CCW direction)
    Currently only works when all components are on the same grid position
    """
    # angle should be a 2d array
    if not len(angle.dims) == 2:
        raise ValueError(f"Expected only two dimensions on `angle`. Got {angle.dims}")
    # assert that all components are on the same position
    print(set(angle.dims))
    print(set(u.dims))
    print(set(v.dims))
    if not (
        set(angle.dims).issubset(set(u.dims)) and set(angle.dims).issubset(set(v.dims))
    ):
        raise ValueError("`u` and `v` need to be on the same grid position as `angle`.")

    # rotate velocities
    theta = np.deg2rad(angle)
    vec = xr.concat([u, v], dim="dim_in")
    # construct rotation matrix
    rot = xr.concat(
        [
            xr.concat([np.cos(theta), np.sin(theta)], dim="dim_out"),
            xr.concat([-np.sin(theta), np.cos(theta)], dim="dim_out"),
        ],
        dim="dim_in",
    )
    rotated_vector = xr.dot(rot, vec, dims="dim_in")
    u_rotated = rotated_vector.isel(dim_out=0)
    v_rotated = rotated_vector.isel(dim_out=1)
    return u_rotated, v_rotated

In [25]:
angle = ds['angle']
old_uo = ds.uo
old_vo = ds.vo
old_tauuo = ds.tauuo
old_tauvo = ds.tauvo
for varname_x, varname_y in [('uo', 'vo'), ('tauuo', 'tauvo')]:
    x_rotated, y_rotated = rotate_vectors(ds[varname_x], ds[varname_y], angle)
    ds[varname_x] = x_rotated.astype(np.float32)
    ds[varname_y] = y_rotated.astype(np.float32)

{'x', 'y'}
{'x', 'y', 'lev', 'time'}
{'x', 'y', 'lev', 'time'}
{'x', 'y'}
{'x', 'y', 'time'}
{'x', 'y', 'time'}


#### Rotation tester

In [26]:
import cartopy.crs as ccrs
import matplotlib
import matplotlib.pyplot as plt
import xarray as xr

def rotated_vectors_qc_plots(u, v, u_rotated, v_rotated):
    roi = dict(lev=0, time=100, y=slice(900, None))
    kwargs = dict(x="lon", y="lat", robust=True, transform=ccrs.PlateCarree())

    fig, axarr = plt.subplots(
        ncols=2,
        nrows=2,
        subplot_kw=dict(projection=ccrs.NorthPolarStereo(), facecolor="gray"),
    )
    u.isel(**roi, missing_dims="warn").plot(ax=axarr.flat[0], **kwargs)
    v.isel(**roi, missing_dims="warn").plot(ax=axarr.flat[1], **kwargs)

    u_rotated.isel(**roi, missing_dims="warn").plot(ax=axarr.flat[2], **kwargs)
    v_rotated.isel(**roi, missing_dims="warn").plot(ax=axarr.flat[3], **kwargs)

    for title, ax in zip(["u", "v", "u rotated", "v rotated"], axarr.flat):
        ax.set_title(title)

    # compare 'seam line'
    fig, axarr = plt.subplots(ncols=2, nrows=2, figsize=[8, 6])

    def fold_and_compare(ax: matplotlib.axes._axes.Axes, seam_data: xr.DataArray):
        middle = len(seam_data.x) // 2
        left = seam_data.isel(y=-1, x=slice(0, middle)).data
        right_flipped = seam_data.isel(y=-1, x=slice(middle, None)).data[::-1]

        ax.plot(left)
        ax.plot(right_flipped, ls="--")

    ax = axarr.flat[0]
    fold_and_compare(ax, u.isel(**roi, missing_dims="warn").load())
    ax.set_ylabel("u")
    ax.set_title("Before rotation: \n should be mirrored")

    ax = axarr.flat[1]
    fold_and_compare(ax, v.isel(**roi, missing_dims="warn").load())
    ax.set_ylabel("v")
    ax.set_title("Before rotation: \n should be mirrored")

    ax = axarr.flat[2]
    fold_and_compare(ax, u_rotated.isel(**roi, missing_dims="warn").load())
    ax.set_ylabel("u")
    ax.set_title("After rotation: \n should be aligned")

    ax = axarr.flat[3]
    fold_and_compare(ax, v_rotated.isel(**roi, missing_dims="warn").load())
    ax.set_ylabel("v")
    ax.set_title("After rotation: \n should be aligned")

    fig.tight_layout()

In [27]:
# rotated_vectors_qc_plots(old_uo, old_vo, ds.uo, ds.vo)
# rotated_vectors_qc_plots(old_tauuo, old_tauvo, ds.tauuo, ds.tauvo)

In [28]:
import numpy as np
import xarray as xr

# Define a small 2D grid
x = np.array([0, 1])
y = np.array([0, 1])

# Create vector components (initially pointing along x-axis)
u = xr.DataArray([[1, 2], [3, 4]], dims=["x", "y"])
v = xr.DataArray([[5, 6], [7, 8]], dims=["x", "y"])

# Create a 90-degree rotation angle array (counterclockwise)
angle = xr.DataArray([[23, 44], [50, 60]], dims=["x", "y"])

# Convert angle to radians
theta = np.deg2rad(angle)

# Stack u and v into a single vector field
vec = xr.concat([u, v], dim="dim_in")  # Shape (x, y, 2)

# Create the 2x2 rotation matrix at each grid point
rot = xr.concat([
    xr.concat([np.cos(theta), np.sin(theta)], dim="dim_out"),
    xr.concat([-np.sin(theta), np.cos(theta)], dim="dim_out")
], dim="dim_in")  # Shape (x, y, 2, 2)

# 1. order: rot * vec
order_1 = xr.dot(rot, vec, dims="dim_in")

# 2. order: vec * rot
order_2 = xr.dot(vec, rot, dims="dim_in")

# 3. Formula
u_rotated_form = u * np.cos(theta) - v * np.sin(theta)
v_rotated_form = u * np.sin(theta) + v * np.cos(theta)

# Print results
print("Original u:\n", u.values)
print("Original v:\n", v.values)
print("\ Order (rot * vec):\n", order_1.isel(dim_out=0), order_1.isel(dim_out=1))
print("\ Order (vec * rot):\n", order_2.isel(dim_out=0), order_2.isel(dim_out=1))
print("\nForm (u * cos(theta) + v * sin(theta)):\n", u_rotated_form)
print("\nForm (v * cos(theta) - u * sin(theta)):\n", v_rotated_form)


Original u:
 [[1 2]
 [3 4]]
Original v:
 [[5 6]
 [7 8]]
\ Order (rot * vec):
 <xarray.DataArray (x: 2, y: 2)>
array([[-1.03315079, -2.72927062],
       [-3.43394827, -4.92820323]])
Dimensions without coordinates: x, y <xarray.DataArray (x: 2, y: 2)>
array([[4.9932554 , 5.70535554],
       [6.7976466 , 7.46410162]])
Dimensions without coordinates: x, y
\ Order (vec * rot):
 <xarray.DataArray (x: 2, y: 2)>
array([[-1.03315079, -2.72927062],
       [-3.43394827, -4.92820323]])
Dimensions without coordinates: x, y <xarray.DataArray (x: 2, y: 2)>
array([[4.9932554 , 5.70535554],
       [6.7976466 , 7.46410162]])
Dimensions without coordinates: x, y

Form (u * cos(theta) + v * sin(theta)):
 <xarray.DataArray (x: 2, y: 2)>
array([[-1.03315079, -2.72927062],
       [-3.43394827, -4.92820323]])
Dimensions without coordinates: x, y

Form (v * cos(theta) - u * sin(theta)):
 <xarray.DataArray (x: 2, y: 2)>
array([[4.9932554 , 5.70535554],
       [6.7976466 , 7.46410162]])
Dimensions without coordi

In [29]:
# Test xr.dot
a = xr.DataArray([[1, 2], [3, 4]], dims=["x", "y"])
b = xr.DataArray([[5, 6], [7, 8]], dims=["x", "y"])
c = xr.dot(a, b, dims="x")
c


<xarray.DataArray (y: 2)>
array([26, 44])
Dimensions without coordinates: y

### Spatial Filtering

In [30]:
import gcm_filters
def spatially_filter(
    ds: xr.Dataset, w_mask, filter_scale=18, depth_dim="lev", y_dim="y", x_dim="x"
):
    """Applies a spatial filter with 3d/2d wetmask depending on the variable dimensions"""
    wmask_3d = (w_mask == 1).astype(int).reset_coords(drop=True)
    depth_indexer = {depth_dim: 0}
    wmask_2d = wmask_3d.isel(**depth_indexer).drop_vars(depth_dim)

    ds_2d, ds_3d = split_2d_3d(ds)
    ds_2d = ds_2d.reset_coords(drop=True)
    ds_3d = ds_3d.reset_coords(drop=True)

    filt_2d = gcm_filters.Filter(
        filter_scale=filter_scale,
        dx_min=1,
        filter_shape=gcm_filters.FilterShape.GAUSSIAN,
        grid_type=gcm_filters.GridType.REGULAR_WITH_LAND,
        grid_vars={"wet_mask": wmask_2d},  # why can gcm filters not accept bool masks?
    )
    filt_3d = gcm_filters.Filter(
        filter_scale=filter_scale,
        dx_min=1,
        filter_shape=gcm_filters.FilterShape.GAUSSIAN,
        grid_type=gcm_filters.GridType.REGULAR_WITH_LAND,
        grid_vars={"wet_mask": wmask_3d},  # why can gcm filters not accept bool masks?
    )
    datasets = [
        filt_2d.apply(ds_2d, dims=[y_dim, x_dim]),
        filt_3d.apply(ds_3d, dims=[y_dim, x_dim]),
    ]
    ds_filtered = xr.merge(datasets)
    # get attrs and coords back
    ds_filtered = ds_filtered.assign_coords({co: ds[co] for co in ds.coords})
    ds_filtered.attrs = ds.attrs
    return ds_filtered


In [31]:
# spatial filtering
ds = spatially_filter(
    ds, ds["wetmask"], depth_dim="lev", y_dim="y", x_dim="x"
)

In [32]:
ds

<xarray.Dataset>
Dimensions:     (time: 14600, x: 1440, y: 1080, lev: 19, ilev: 20, y_b: 1081,
                 x_b: 1441)
Coordinates: (12/13)
  * time        (time) object 0151-01-06 00:00:00 ... 0351-01-01 00:00:00
  * x           (x) float64 -299.7 -299.5 -299.2 -299.0 ... 59.53 59.78 60.03
  * y           (y) float64 -80.39 -80.31 -80.23 -80.15 ... 89.73 89.84 89.95
  * lev         (lev) float64 2.5 10.0 22.5 40.0 ... 3.1e+03 4e+03 5e+03 6e+03
    dz          (lev) int64 5 10 15 20 30 50 70 ... 500 600 800 1000 1000 1000
  * ilev        (ilev) float64 0.0 5.0 15.0 30.0 ... 4.5e+03 5.5e+03 6.5e+03
    ...          ...
    lon         (y, x) float64 -299.7 -299.5 -299.2 -299.0 ... 60.0 60.0 60.0
    lat         (y, x) float64 -79.81 -79.81 -79.8 -79.8 ... 64.33 64.22 64.11
    angle       (y, x) float64 1.934 1.911 1.888 1.864 ... -89.77 -89.77 -89.77
    wetmask     (lev, y, x) bool dask.array<chunksize=(1, 1080, 1440), meta=np.ndarray>
    lat_b       (y_b, x_b) float64 -79.84 -79.84 -79.84 ... 64.28 64.17 64.06
    lon_b       (y_b, x_b) float64 -299.8 -299.6 -299.3 ... 60.0 60.0 60.0
Dimensions without coordinates: y_b, x_b
Data variables: (12/22)
    evs         (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfds        (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hflso       (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfsifrazil  (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    hfsso       (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    prlq        (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    ...          ...
    wfo         (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    zos         (time, y, x) float32 dask.array<chunksize=(10, 1080, 1440), meta=np.ndarray>
    so          (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>
    thetao      (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>
    uo          (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>
    vo          (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 1080, 1440), meta=np.ndarray>

### Horizontal Regridding

In [33]:
# regrid
ds_target_grid = gaussian_grid

# TODO: remove target grid dimension assumptions
ds_target_grid = ds_target_grid.rename(
    {
        "grid_x": "x_b",
        "grid_y": "y_b",
        "grid_xt": "x",
        "grid_yt": "y",
        "grid_lon": "lon_b",
        "grid_lat": "lat_b",
        "grid_lont": "lon",
        "grid_latt": "lat",
    }
)

In [34]:
import xesmf as xe
    
def horizontal_regrid(ds, ds_target):
    """Regrid `ds` horizontally, and conserve the integral in space"""
    regridder_kwargs = dict(ignore_degenerate=True, periodic=True, unmapped_to_nan=True)

    # try to run this with higher precision (TODO: Test if this actually makes a difference).
    s = xr.Dataset(
        coords={
            co: ds[co].astype("float128") for co in ["lon", "lat", "lon_b", "lat_b"]
        }
    )
    t = xr.Dataset(
        coords={
            co: ds_target[co].astype("float128")
            for co in ["lon", "lat", "lon_b", "lat_b"]
        }
    )

    regridder = xe.Regridder(s, t, "conservative", **regridder_kwargs)
    ds_regridded = regridder(ds, skipna=True, na_thres=1)

    # get lon/lats from the target grid
    lon = ds_target.lon
    lat = ds_target.lat

    lon_b = ds_target.lon_b
    lat_b = ds_target.lat_b

    # get x and y values
    x = lon.isel(y=0)
    y = lat.isel(x=0)

    # calculate new area
    r_earth = 6356  # in km
    new_area = xe.util.cell_area(ds_target, r_earth) * 1e6

    ## calculate the wetmask afterwards...
    wetmask = ~np.isnan(ds_regridded.thetao.isel(time=0).drop_vars("time")).load()
    ocean_frac = regridder(ds.wetmask.astype("float64")).fillna(0.0)

    ds_regridded = ds_regridded.drop_vars(["lon_b", "lat_b"])
    ds_regridded = ds_regridded.assign_coords(
        lon=lon,
        lat=lat,
        lon_b=lon_b,
        lat_b=lat_b,
        areacello=new_area,
        x=x,
        y=y,
        wetmask=wetmask,
        ocean_fraction=ocean_frac,
    )
    ds_regridded.attrs = ds.attrs | ds_regridded.attrs

    return ds_regridded


In [35]:
ds_regridded = horizontal_regrid(ds, ds_target_grid).astype("float32")
print(f"Regridded size: {ds_regridded.nbytes / 1e9:.1f} GB")
ds_regridded

Regridded size: 355.7 GB


<xarray.Dataset>
Dimensions:         (time: 14600, y: 180, x: 360, lev: 19, ilev: 20, y_b: 181,
                     x_b: 361)
Coordinates: (12/13)
  * time            (time) object 0151-01-06 00:00:00 ... 0351-01-01 00:00:00
  * lev             (lev) float64 2.5 10.0 22.5 40.0 ... 4e+03 5e+03 6e+03
    dz              (lev) int64 5 10 15 20 30 50 ... 500 600 800 1000 1000 1000
  * ilev            (ilev) float64 0.0 5.0 15.0 30.0 ... 4.5e+03 5.5e+03 6.5e+03
    lat             (y, x) float64 -89.24 -89.24 -89.24 ... 89.24 89.24 89.24
    lon             (y, x) float64 0.5 1.5 2.5 3.5 ... 356.5 357.5 358.5 359.5
    ...              ...
    lat_b           (y_b, x_b) float64 -90.0 -90.0 -90.0 ... 90.0 90.0 90.0
    areacello       (y, x) float64 1.699e+08 1.699e+08 ... 1.699e+08 1.699e+08
  * x               (x) float64 0.5 1.5 2.5 3.5 4.5 ... 356.5 357.5 358.5 359.5
  * y               (y) float64 -89.24 -88.25 -87.25 ... 87.25 88.25 89.24
    wetmask         (lev, y, x) bool False False False ... False False False
    ocean_fraction  (lev, y, x) float64 dask.array<chunksize=(1, 180, 360), meta=np.ndarray>
Dimensions without coordinates: y_b, x_b
Data variables: (12/22)
    evs             (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    hfds            (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    hflso           (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    hfsifrazil      (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    hfsso           (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    prlq            (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    ...              ...
    wfo             (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    zos             (time, y, x) float32 dask.array<chunksize=(10, 180, 360), meta=np.ndarray>
    so              (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 180, 360), meta=np.ndarray>
    thetao          (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 180, 360), meta=np.ndarray>
    uo              (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 180, 360), meta=np.ndarray>
    vo              (time, lev, y, x) float32 dask.array<chunksize=(10, 1, 180, 360), meta=np.ndarray>
Attributes:
    regrid_method:  conservative

### Continue

In [37]:
ds = ds_regridded
for var, attrs in attrs.items():
    ds[var].attrs = attrs

wetmask = ds["wetmask"].astype(np.float32)
if len(wetmask.attrs) == 0:
    wetmask.attrs["long_name"] = "ocean mask"
    wetmask.attrs["units"] = "0 if land, 1 if ocean"

ds["mask"] = wetmask
vars_3d = list(["thetao", "so", "uo", "vo"]) + ["mask"]

for i, _ in enumerate(ds['lev'].values):
    for var in vars_3d:
        long_name = ds[var].long_name
        ds[f"{var}_{i}"] = ds[var].isel({'lev': i})
        ds[f"{var}_{i}"].attrs["long_name"] = long_name + f" level-{i}"

ds = ds.drop_vars(vars_3d)
ds = ds.drop_dims('lev')
ds = ds.reset_coords(drop=True)
ds = xr.merge([ds, idepth_ds])

# add 'sst' variable in degrees Kelvin
ds["sst"] = ds['tos'].copy() + 273.15
ds["sst"].attrs["long_name"] = "Sea surface temperature"
ds["sst"].attrs["units"] = "K"

    
chunks = {'time': 10, 'x': 180, 'y': 180}
ds = ds.chunk(chunks)

drop_dims = [x for x in list(ds.dims) if x not in ['x', 'y', 'time']]
ds = ds.drop_dims(drop_dims)
# ds = config.rename(ds)
ds


KeyError: 'cell_measures'